-- Automatically Generated by Espalier

local L = assert(require "lpeg")
local P, V, S = L.P, L.V, L.S
local R = L.R
local C, Cg, Cb, Cmt = L.C, L.Cg, L.Cb, L.Cmt

local function _sql_fn(_ENV)
   START 'sql'

   SUPPRESS ("statement", "semi", "t_opt", "affinity", "fluff",
            "conflict_clause", "indexed_columns", "fk_on_clause", "expr_atom",
             "literal_value", "digit", "higit", "quoted", "id", "bare_name",
            "lead_char", "follow_char", "A", "B", "C", "D", "E", "F", "G", "H"
            , "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U",
             "V", "W", "X", "Y", "Z", "_", "ws", "dent", "WS", "comment",
            "line_comment", "block_comment", "t")

   _ENV["sql"] = V"_" * ( V"statement" * V"_" * V"semi" * V"_" )^1

   _ENV["statement"] = V"explain"^-1 * ( V"alter_table" + V"analyze" +
                                       V"attach" + V"begin" + V"commit" +
                                       V"create_index" + V"create_table" +
                                       V"create_trigger" + V"create_view" +
                                       V"create_virtual_table" + V"delete" +
                                       V"detach" + V"drop" + V"insert" +
                                       V"pragma" + V"reindex" + V"release" +
                                       V"rollback" + V"savepoint" + V"select"
                                       + V"update" + V"vacuum" )

   _ENV["semi"] = P";" + -1

   _ENV["explain"] = V"EXPLAIN" * ( V"QUERY" * V"PLAN" )^-1

   _ENV["create_table"] = V"CREATE" * ( V"TEMP" + V"TEMPORARY" )^-1 * V"TABLE"
                          * ( V"IF" * V"NOT" * V"EXISTS" )^-1 * (
                                                                V"schema_name"
                                                                * V"_" * P"."
                                                                * V"_" )^-1 *
                          V"table_name" * V"_" * ( V"AS" * V"select" + P"(" *
                                                 V"_" * V"column_def" * ( V"_"
                                                                        * P","
                                                                        * V"_"
                                                                        *
                                                                 V"column_def"
                                                                        )^0 *
                                                 ( V"_" * P"," * ( V"_" *
                                                           V"table_constraint"
                                                                 )^1 )^-1 *
                                                 V"_" * P")" * V"_" *
                                                 V"table_options"^0 )

   _ENV["schema_name"] = V"name"

   _ENV["table_name"] = V"name"

   _ENV["table_options"] = V"t_opt" * ( P"," * V"_" * V"t_opt" )^0

   _ENV["t_opt"] = ( V"WITHOUT" * V"ROWID" + V"STRICT" )

   _ENV["column_def"] = V"column_name" * V"_" * ( V"type_name" )^-1 * ( V"_" *

                                                          V"column_constraint"
                                                                      )^0

   _ENV["column_name"] = V"name"

   _ENV["type_name"] = ( V"affinity" * V"_" ) * V"fluff"^-1

   _ENV["affinity"] = V"name" * ( V"_" * V"name" )^0

   _ENV["fluff"] = P"(" * V"_" * V"signed_number" * V"_" * P")" * V"_" + P"("
                   * V"_" * V"signed_number" * V"_" * P"," * V"_" *
                   V"signed_number" * V"_" * P")" * V"_"

   _ENV["column_constraint"] = V"CONSTRAINT" * V"name" * V"_" + V"NOT" *
                               V"NULL" + V"PRIMARY" * V"KEY" * ( V"ASC" +
                                                               V"DESC" )^-1 *
                               V"conflict_clause"^-1 * V"AUTOINCREMENT"^-1 +
                               V"UNIQUE" * V"conflict_clause"^-1 + V"CHECK" *
                               V"group_expr" + V"DEFAULT" * ( V"literal_value"
                                                            + V"group_expr" +
                                                            V"signed_number" )
                               + V"COLLATE" * V"collation_name" +
                               V"foreign_key_clause" + ( V"GENERATED" *
                                                       V"ALWAYS" )^-1 * V"AS"
                               * V"group_expr" * ( V"STORED" + V"VIRTUAL" )^-1


   _ENV["table_constraint"] = V"CONSTRAINT" * V"name" * V"_" + V"FOREIGN" *
                              V"KEY" * P"(" * V"_" * V"column_names" * P")" *
                              V"_" * V"foreign_key_clause" + ( V"PRIMARY" *
                                                             V"KEY" +
                                                             V"UNIQUE" ) *
                              P"(" * V"_" * V"indexed_columns" * P")" * V"_" *
                              V"conflict_clause" + V"CHECK" * V"group_expr"

   _ENV["conflict_clause"] = V"ON" * V"CONFLICT" * ( V"ROLLBACK" + V"ABORT" +
                                                   V"FAIL" + V"IGNORE" +
                                                   V"REPLACE" )

   _ENV["column_names"] = V"column_name" * V"_" * ( P"," * V"_" *
                                                  V"column_name" * V"_" )^0

   _ENV["indexed_columns"] = V"indexed_column" * ( P"," * V"_" *
                                                 V"indexed_column" )^0

   _ENV["indexed_column"] = ( V"column_name" + V"expr" ) * V"_" * ( V"COLLATE"
                                                                  * V"name" *
                                                                  V"_" )^-1 *
                            ( V"ASC" + V"DESC" )^-1

   _ENV["group_expr"] = P"(" * V"_" * V"expr" * V"_" * P")" * V"_"

   _ENV["foreign_key_clause"] = V"REFERENCES" * V"table_name" * V"_" * ( P"("
                                                                       * V"_"
                                                                       *
                                                               V"column_names"
                                                                       * P")"
                                                                       * V"_"
                                                                       )^-1 *
                                V"fk_on_clause"^0 * ( V"NOT"^-1 *
                                                    V"DEFERRABLE" * (
                                                                  V"INITIALLY"
                                                                    * (
                                                                   V"DEFERRED"
                                                                      +
                                                                  V"IMMEDIATE"
                                                                      ) )^-1 )
                                ^-1

   _ENV["fk_on_clause"] = ( V"ON" * ( V"DELETE" + V"UPDATE" ) * ( V"SET" * (
                                                                       V"NULL"
                                                                           +
                                                                    V"DEFAULT"
                                                                           ) +
                                                                V"CASCADE" +
                                                                V"RESTRICT" +
                                                                V"NO" *
                                                                V"ACTION" ) )
                          * V"_" + V"MATCH" * V"name" * V"_"

   _ENV["expr"] = V"expr_atom"

   _ENV["expr_atom"] = V"literal_value" + V"bind_parameter" + V"CAST" * P"(" *
                       V"_" * V"expr" * V"AS" * V"type_name" * V"_" * P")" +
                       V"NOT" * V"EXISTS" * P"(" * V"_" * V"select" * P")" +
                       V"function_expr" + V"raise_function"

   _ENV["function_expr"] = V"function_name" * P"(" * V"_" * ( P"*" + (
                                                                   V"DISTINCT"
                                                                     ^-1 *
                                                                  V"expr_list"
                                                                     ) )^1 *
                           V"_" * P")" * V"_" * V"filter_clause"^-1 *
                           V"over_clause"^-1

   _ENV["function_name"] = V"name"

   _ENV["expr_list"] = V"expr" * ( V"_" * P"," * V"_" * V"expr" )^0

   _ENV["literal_value"] = ( V"number" + V"string" + V"blob" + V"NULL" +
                           V"TRUE" + V"FALSE" + V"CURRENT_TIMESTAMP" +
                           V"CURRENT_TIME" + V"CURRENT_DATE" )

   _ENV["signed_number"] = S"+-" * V"number"

   _ENV["number"] = V"real" + V"hex" + V"integer"

   _ENV["real"] = ( ( V"integer" * ( P"." * V"fraction" ) ) + ( P"." *
                                                              V"fraction" ) )
                  * ( ( P"e" + P"E" ) * P"-"^-1 * V"exponent" )^-1

   _ENV["hex"] = P"0" * S"Xx" * V"higit"^1 * ( P"." * V"higit"^0 )^-1

   _ENV["integer"] = V"digit"^1

   _ENV["fraction"] = V"digit"^1

   _ENV["exponent"] = V"digit"^1

   _ENV["digit"] = R"09"

   _ENV["higit"] = V"digit" + R"af" + R"AF"

   _ENV["string"] = P"'" * ( ( -( P"'" ) * 1 ) + P"''" )^0 * P"'"

   _ENV["blob"] = S"xX" * P"'" * V"higit"^0 * P"'"

   _ENV["name"] = V"quoted" + V"id"

   _ENV["quoted"] = P'"' * V"quote_name" * P'"' + P"[" * V"quote_name" * P"]"
                    + P"`" * V"quote_name" * P"`"

   _ENV["id"] = -( V"keyword" ) * V"bare_name"

   _ENV["bare_name"] = V"lead_char" * V"follow_char"^0

   _ENV["lead_char"] = R"\x80\xff" + R"AZ" + R"az" + P"_"

   _ENV["follow_char"] = V"lead_char" + R"09" + P"$"

   _ENV["quote_name"] = ( -( P'"' ) * 1 )^1

   _ENV["ABORT"] = V"A" * V"B" * V"O" * V"R" * V"T" * V"t" * V"_"

   _ENV["ACTION"] = V"A" * V"C" * V"T" * V"I" * V"O" * V"N" * V"t" * V"_"

   _ENV["ADD"] = V"A" * V"D" * V"D" * V"t" * V"_"

   _ENV["AFTER"] = V"A" * V"F" * V"T" * V"E" * V"R" * V"t" * V"_"

   _ENV["ALL"] = V"A" * V"L" * V"L" * V"t" * V"_"

   _ENV["ALTER"] = V"A" * V"L" * V"T" * V"E" * V"R" * V"t" * V"_"

   _ENV["ALWAYS"] = V"A" * V"L" * V"W" * V"A" * V"Y" * V"S" * V"t" * V"_"

   _ENV["ANALYZE"] = V"A" * V"N" * V"A" * V"L" * V"Y" * V"Z" * V"E" * V"t" *
                     V"_"

   _ENV["AND"] = V"A" * V"N" * V"D" * V"t" * V"_"

   _ENV["ASC"] = V"A" * V"S" * V"C" * V"t" * V"_"

   _ENV["AS"] = V"A" * V"S" * V"t" * V"_"

   _ENV["ATTACH"] = V"A" * V"T" * V"T" * V"A" * V"C" * V"H" * V"t" * V"_"

   _ENV["AUTOINCREMENT"] = V"A" * V"U" * V"T" * V"O" * V"I" * V"N" * V"C" *
                           V"R" * V"E" * V"M" * V"E" * V"N" * V"T" * V"t" *
                           V"_"

   _ENV["BEFORE"] = V"B" * V"E" * V"F" * V"O" * V"R" * V"E" * V"t" * V"_"

   _ENV["BEGIN"] = V"B" * V"E" * V"G" * V"I" * V"N" * V"t" * V"_"

   _ENV["BETWEEN"] = V"B" * V"E" * V"T" * V"W" * V"E" * V"E" * V"N" * V"t" *
                     V"_"

   _ENV["BY"] = V"B" * V"Y" * V"t" * V"_"

   _ENV["CASCADE"] = V"C" * V"A" * V"S" * V"C" * V"A" * V"D" * V"E" * V"t" *
                     V"_"

   _ENV["CASE"] = V"C" * V"A" * V"S" * V"E" * V"t" * V"_"

   _ENV["CAST"] = V"C" * V"A" * V"S" * V"T" * V"t" * V"_"

   _ENV["CHECK"] = V"C" * V"H" * V"E" * V"C" * V"K" * V"t" * V"_"

   _ENV["COLLATE"] = V"C" * V"O" * V"L" * V"L" * V"A" * V"T" * V"E" * V"t" *
                     V"_"

   _ENV["COLUMN"] = V"C" * V"O" * V"L" * V"U" * V"M" * V"N" * V"t" * V"_"

   _ENV["COMMIT"] = V"C" * V"O" * V"M" * V"M" * V"I" * V"T" * V"t" * V"_"

   _ENV["CONFLICT"] = V"C" * V"O" * V"N" * V"F" * V"L" * V"I" * V"C" * V"T" *
                      V"t" * V"_"

   _ENV["CONSTRAINT"] = V"C" * V"O" * V"N" * V"S" * V"T" * V"R" * V"A" * V"I"
                        * V"N" * V"T" * V"t" * V"_"

   _ENV["CREATE"] = V"C" * V"R" * V"E" * V"A" * V"T" * V"E" * V"t" * V"_"

   _ENV["CROSS"] = V"C" * V"R" * V"O" * V"S" * V"S" * V"t" * V"_"

   _ENV["CURRENT_DATE"] = V"C" * V"U" * V"R" * V"R" * V"E" * V"N" * V"T" *
                          P"_" * V"D" * V"A" * V"T" * V"E" * V"t" * V"_"

   _ENV["CURRENT_TIMESTAMP"] = V"C" * V"U" * V"R" * V"R" * V"E" * V"N" * V"T"
                               * P"_" * V"T" * V"I" * V"M" * V"E" * V"S" *
                               V"T" * V"A" * V"M" * V"P" * V"t" * V"_"

   _ENV["CURRENT_TIME"] = V"C" * V"U" * V"R" * V"R" * V"E" * V"N" * V"T" *
                          P"_" * V"T" * V"I" * V"M" * V"E" * V"t" * V"_"

   _ENV["DATABASE"] = V"D" * V"A" * V"T" * V"A" * V"B" * V"A" * V"S" * V"E" *
                      V"t" * V"_"

   _ENV["DEFAULT"] = V"D" * V"E" * V"F" * V"A" * V"U" * V"L" * V"T" * V"t" *
                     V"_"

   _ENV["DEFERRABLE"] = V"D" * V"E" * V"F" * V"E" * V"R" * V"R" * V"A" * V"B"
                        * V"L" * V"E" * V"t" * V"_"

   _ENV["DEFERRED"] = V"D" * V"E" * V"F" * V"E" * V"R" * V"R" * V"E" * V"D" *
                      V"t" * V"_"

   _ENV["DELETE"] = V"D" * V"E" * V"L" * V"E" * V"T" * V"E" * V"t" * V"_"

   _ENV["DESC"] = V"D" * V"E" * V"S" * V"C" * V"t" * V"_"

   _ENV["DETACH"] = V"D" * V"E" * V"T" * V"A" * V"C" * V"H" * V"t" * V"_"

   _ENV["DISTINCT"] = V"D" * V"I" * V"S" * V"T" * V"I" * V"N" * V"C" * V"T" *
                      V"t" * V"_"

   _ENV["DROP"] = V"D" * V"R" * V"O" * V"P" * V"t" * V"_"

   _ENV["EACH"] = V"E" * V"A" * V"C" * V"H" * V"t" * V"_"

   _ENV["ELSE"] = V"E" * V"L" * V"S" * V"E" * V"t" * V"_"

   _ENV["END"] = V"E" * V"N" * V"D" * V"t" * V"_"

   _ENV["ESCAPE"] = V"E" * V"S" * V"C" * V"A" * V"P" * V"E" * V"t" * V"_"

   _ENV["EXCEPT"] = V"E" * V"X" * V"C" * V"E" * V"P" * V"T" * V"t" * V"_"

   _ENV["EXCLUSIVE"] = V"E" * V"X" * V"C" * V"L" * V"U" * V"S" * V"I" * V"V" *
                       V"E" * V"t" * V"_"

   _ENV["EXISTS"] = V"E" * V"X" * V"I" * V"S" * V"T" * V"S" * V"t" * V"_"

   _ENV["EXPLAIN"] = V"E" * V"X" * V"P" * V"L" * V"A" * V"I" * V"N" * V"t" *
                     V"_"

   _ENV["FAIL"] = V"F" * V"A" * V"I" * V"L" * V"t" * V"_"

   _ENV["FALSE"] = V"F" * V"A" * V"L" * V"S" * V"E" * V"t" * V"_"

   _ENV["FOREIGN"] = V"F" * V"O" * V"R" * V"E" * V"I" * V"G" * V"N" * V"t" *
                     V"_"

   _ENV["FOR"] = V"F" * V"O" * V"R" * V"t" * V"_"

   _ENV["FROM"] = V"F" * V"R" * V"O" * V"M" * V"t" * V"_"

   _ENV["FULL"] = V"F" * V"U" * V"L" * V"L" * V"t" * V"_"

   _ENV["GENERATED"] = V"G" * V"E" * V"N" * V"E" * V"R" * V"A" * V"T" * V"E" *
                       V"D" * V"t" * V"_"

   _ENV["GLOB"] = V"G" * V"L" * V"O" * V"B" * V"t" * V"_"

   _ENV["GROUP"] = V"G" * V"R" * V"O" * V"U" * V"P" * V"t" * V"_"

   _ENV["HAVING"] = V"H" * V"A" * V"V" * V"I" * V"N" * V"G" * V"t" * V"_"

   _ENV["IF"] = V"I" * V"F" * V"t" * V"_"

   _ENV["IGNORE"] = V"I" * V"G" * V"N" * V"O" * V"R" * V"E" * V"t" * V"_"

   _ENV["IMMEDIATE"] = V"I" * V"M" * V"M" * V"E" * V"D" * V"I" * V"A" * V"T" *
                       V"E" * V"t" * V"_"

   _ENV["INDEX"] = V"I" * V"N" * V"D" * V"E" * V"X" * V"t" * V"_"

   _ENV["INITIALLY"] = V"I" * V"N" * V"I" * V"T" * V"I" * V"A" * V"L" * V"L" *
                       V"Y" * V"t" * V"_"

   _ENV["INNER"] = V"I" * V"N" * V"N" * V"E" * V"R" * V"t" * V"_"

   _ENV["INSERT"] = V"I" * V"N" * V"S" * V"E" * V"R" * V"T" * V"t" * V"_"

   _ENV["INSTEAD"] = V"I" * V"N" * V"S" * V"T" * V"E" * V"A" * V"D" * V"t" *
                     V"_"

   _ENV["INTERSECT"] = V"I" * V"N" * V"T" * V"E" * V"R" * V"S" * V"E" * V"C" *
                       V"T" * V"t" * V"_"

   _ENV["INTO"] = V"I" * V"N" * V"T" * V"O" * V"t" * V"_"

   _ENV["IN"] = V"I" * V"N" * V"t" * V"_"

   _ENV["ISNULL"] = V"I" * V"S" * V"N" * V"U" * V"L" * V"L" * V"t" * V"_"

   _ENV["IS"] = V"I" * V"S" * V"t" * V"_"

   _ENV["JOIN"] = V"J" * V"O" * V"I" * V"N" * V"t" * V"_"

   _ENV["KEY"] = V"K" * V"E" * V"Y" * V"t" * V"_"

   _ENV["LEFT"] = V"L" * V"E" * V"F" * V"T" * V"t" * V"_"

   _ENV["LIKE"] = V"L" * V"I" * V"K" * V"E" * V"t" * V"_"

   _ENV["LIMIT"] = V"L" * V"I" * V"M" * V"I" * V"T" * V"t" * V"_"

   _ENV["MATCH"] = V"M" * V"A" * V"T" * V"C" * V"H" * V"t" * V"_"

   _ENV["NATURAL"] = V"N" * V"A" * V"T" * V"U" * V"R" * V"A" * V"L" * V"t" *
                     V"_"

   _ENV["NOTNULL"] = V"N" * V"O" * V"T" * V"N" * V"U" * V"L" * V"L" * V"t" *
                     V"_"

   _ENV["NOT"] = V"N" * V"O" * V"T" * V"t" * V"_"

   _ENV["NO"] = V"N" * V"O" * V"t" * V"_"

   _ENV["NULL"] = V"N" * V"U" * V"L" * V"L" * V"t" * V"_"

   _ENV["OFFSET"] = V"O" * V"F" * V"F" * V"S" * V"E" * V"T" * V"t" * V"_"

   _ENV["OF"] = V"O" * V"F" * V"t" * V"_"

   _ENV["ON"] = V"O" * V"N" * V"t" * V"_"

   _ENV["ORDER"] = V"O" * V"R" * V"D" * V"E" * V"R" * V"t" * V"_"

   _ENV["OR"] = V"O" * V"R" * V"t" * V"_"

   _ENV["OUTER"] = V"O" * V"U" * V"T" * V"E" * V"R" * V"t" * V"_"

   _ENV["PLAN"] = V"P" * V"L" * V"A" * V"N" * V"t" * V"_"

   _ENV["PRAGMA"] = V"P" * V"R" * V"A" * V"G" * V"M" * V"A" * V"t" * V"_"

   _ENV["PRIMARY"] = V"P" * V"R" * V"I" * V"M" * V"A" * V"R" * V"Y" * V"t" *
                     V"_"

   _ENV["QUERY"] = V"Q" * V"U" * V"E" * V"R" * V"Y" * V"t" * V"_"

   _ENV["REFERENCES"] = V"R" * V"E" * V"F" * V"E" * V"R" * V"E" * V"N" * V"C"
                        * V"E" * V"S" * V"t" * V"_"

   _ENV["RAISE"] = V"R" * V"A" * V"I" * V"S" * V"E" * V"t" * V"_"

   _ENV["REGEXP"] = V"R" * V"E" * V"G" * V"E" * V"X" * V"P" * V"t" * V"_"

   _ENV["REINDEX"] = V"R" * V"E" * V"I" * V"N" * V"D" * V"E" * V"X" * V"t" *
                     V"_"

   _ENV["RENAME"] = V"R" * V"E" * V"N" * V"A" * V"M" * V"E" * V"t" * V"_"

   _ENV["REPLACE"] = V"R" * V"E" * V"P" * V"L" * V"A" * V"C" * V"E" * V"t" *
                     V"_"

   _ENV["RESTRICT"] = V"R" * V"E" * V"S" * V"T" * V"R" * V"I" * V"C" * V"T" *
                      V"t" * V"_"

   _ENV["RIGHT"] = V"R" * V"I" * V"G" * V"H" * V"T" * V"t" * V"_"

   _ENV["ROLLBACK"] = V"R" * V"O" * V"L" * V"L" * V"B" * V"A" * V"C" * V"K" *
                      V"t" * V"_"

   _ENV["ROWID"] = V"R" * V"O" * V"W" * V"I" * V"D" * V"t" * V"_"

   _ENV["ROW"] = V"R" * V"O" * V"W" * V"t" * V"_"

   _ENV["SELECT"] = V"S" * V"E" * V"L" * V"E" * V"C" * V"T" * V"t" * V"_"

   _ENV["SET"] = V"S" * V"E" * V"T" * V"t" * V"_"

   _ENV["STORED"] = V"S" * V"T" * V"O" * V"R" * V"E" * V"D" * V"t" * V"_"

   _ENV["STRICT"] = V"S" * V"T" * V"R" * V"I" * V"C" * V"T" * V"t" * V"_"

   _ENV["TABLE"] = V"T" * V"A" * V"B" * V"L" * V"E" * V"t" * V"_"

   _ENV["TEMPORARY"] = V"T" * V"E" * V"M" * V"P" * V"O" * V"R" * V"A" * V"R" *
                       V"Y" * V"t" * V"_"

   _ENV["TEMP"] = V"T" * V"E" * V"M" * V"P" * V"t" * V"_"

   _ENV["THEN"] = V"T" * V"H" * V"E" * V"N" * V"t" * V"_"

   _ENV["TO"] = V"T" * V"O" * V"t" * V"_"

   _ENV["TRANSACTION"] = V"T" * V"R" * V"A" * V"N" * V"S" * V"A" * V"C" * V"T"
                         * V"I" * V"O" * V"N" * V"t" * V"_"

   _ENV["TRIGGER"] = V"T" * V"R" * V"I" * V"G" * V"G" * V"E" * V"R" * V"t" *
                     V"_"

   _ENV["TRUE"] = V"T" * V"R" * V"U" * V"E" * V"t" * V"_"

   _ENV["UNION"] = V"U" * V"N" * V"I" * V"O" * V"N" * V"t" * V"_"

   _ENV["UNIQUE"] = V"U" * V"N" * V"I" * V"Q" * V"U" * V"E" * V"t" * V"_"

   _ENV["UPDATE"] = V"U" * V"P" * V"D" * V"A" * V"T" * V"E" * V"t" * V"_"

   _ENV["USING"] = V"U" * V"S" * V"I" * V"N" * V"G" * V"t" * V"_"

   _ENV["VACUUM"] = V"V" * V"A" * V"C" * V"U" * V"U" * V"M" * V"t" * V"_"

   _ENV["VALUES"] = V"V" * V"A" * V"L" * V"U" * V"E" * V"S" * V"t" * V"_"

   _ENV["VIEW"] = V"V" * V"I" * V"E" * V"W" * V"t" * V"_"

   _ENV["VIRTUAL"] = V"V" * V"I" * V"R" * V"T" * V"U" * V"A" * V"L" * V"t" *
                     V"_"

   _ENV["WHEN"] = V"W" * V"H" * V"E" * V"N" * V"t" * V"_"

   _ENV["WHERE"] = V"W" * V"H" * V"E" * V"R" * V"E" * V"t" * V"_"

   _ENV["WITHOUT"] = V"W" * V"I" * V"T" * V"H" * V"O" * V"U" * V"T" * V"t" *
                     V"_"

   _ENV["keyword"] = ( V"ABORT" + V"ACTION" + V"ADD" + V"AFTER" + V"ALL" +
                     V"ALTER" + V"ALWAYS" + V"ANALYZE" + V"AND" + V"ASC" +
                     V"AS" + V"ATTACH" + V"AUTOINCREMENT" + V"BEFORE" +
                     V"BEGIN" + V"BETWEEN" + V"BY" + V"CASCADE" + V"CASE" +
                     V"CAST" + V"CHECK" + V"COLLATE" + V"COLUMN" + V"COMMIT" +
                     V"CONFLICT" + V"CONSTRAINT" + V"CREATE" + V"CROSS" +
                     V"CURRENT_DATE" + V"CURRENT_TIMESTAMP" + V"CURRENT_TIME"
                     + V"DATABASE" + V"DEFAULT" + V"DEFERRABLE" + V"DEFERRED"
                     + V"DELETE" + V"DESC" + V"DETACH" + V"DISTINCT" + V"DROP"
                     + V"EACH" + V"ELSE" + V"END" + V"ESCAPE" + V"EXCEPT" +
                     V"EXCLUSIVE" + V"EXISTS" + V"EXPLAIN" + V"FAIL" +
                     V"FALSE" + V"FOREIGN" + V"FOR" + V"FROM" + V"FULL" +
                     V"GENERATED" + V"GLOB" + V"GROUP" + V"HAVING" + V"IF" +
                     V"IGNORE" + V"IMMEDIATE" + V"INDEX" + V"INITIALLY" +
                     V"INNER" + V"INSERT" + V"INSTEAD" + V"INTERSECT" +
                     V"INTO" + V"IN" + V"ISNULL" + V"IS" + V"JOIN" + V"KEY" +
                     V"LEFT" + V"LIKE" + V"LIMIT" + V"MATCH" + V"NATURAL" +
                     V"NOTNULL" + V"NOT" + V"NO" + V"NULL" + V"OFFSET" + V"OF"
                     + V"ON" + V"ORDER" + V"OR" + V"OUTER" + V"PLAN" +
                     V"PRAGMA" + V"PRIMARY" + V"QUERY" + V"REFERENCES" +
                     V"RAISE" + V"REGEXP" + V"REINDEX" + V"RENAME" +
                     V"REPLACE" + V"RESTRICT" + V"RIGHT" + V"ROLLBACK" +
                     V"ROWID" + V"ROW" + V"SELECT" + V"SET" + V"STORED" +
                     V"STRICT" + V"TABLE" + V"TEMPORARY" + V"TEMP" + V"THEN" +
                     V"TO" + V"TRANSACTION" + V"TRIGGER" + V"TRUE" + V"UNION"
                     + V"UNIQUE" + V"UPDATE" + V"USING" + V"VACUUM" +
                     V"VALUES" + V"VIEW" + V"VIRTUAL" + V"WHEN" + V"WHERE" +
                     V"WITHOUT" )

   _ENV["A"] = S"Aa"

   _ENV["B"] = S"Bb"

   _ENV["C"] = S"Cc"

   _ENV["D"] = S"Dd"

   _ENV["E"] = S"Ee"

   _ENV["F"] = S"Ff"

   _ENV["G"] = S"Gg"

   _ENV["H"] = S"Hh"

   _ENV["I"] = S"Ii"

   _ENV["J"] = S"Ji"

   _ENV["K"] = S"Kk"

   _ENV["L"] = S"Ll"

   _ENV["M"] = S"Mm"

   _ENV["N"] = S"Nn"

   _ENV["O"] = S"Oo"

   _ENV["P"] = S"Pp"

   _ENV["Q"] = S"Qq"

   _ENV["R"] = S"Rr"

   _ENV["S"] = S"Ss"

   _ENV["T"] = S"Tt"

   _ENV["U"] = S"Uu"

   _ENV["V"] = S"Vv"

   _ENV["W"] = S"Ww"

   _ENV["X"] = S"Xx"

   _ENV["Y"] = S"Yy"

   _ENV["Z"] = S"Zz"

   _ENV["_"] = V"ws"^0

   _ENV["ws"] = ( V"comment" + V"dent" + V"WS" )^1

   _ENV["dent"] = P"\n" * ( -( P"\n" ) * V"WS" )^0

   _ENV["WS"] = S"\x09\x0a\x0c\x0d\x20"

   _ENV["comment"] = V"line_comment" + V"block_comment"

   _ENV["line_comment"] = P"--" * ( -( P"\n" ) * 1 )^0

   _ENV["block_comment"] = P"/*" * ( -( P"*/" ) * 1 )^0 * ( P"*/" + -1 )

   _ENV["t"] = -( V"follow_char" )

   _ENV["alter_table"] = V"_" * P"alter" * S"-_" * P"table" * V"_"

   _ENV["analyze"] = V"_" * P"analyze" * V"_"

   _ENV["attach"] = V"_" * P"attach" * V"_"

   _ENV["begin"] = V"_" * P"begin" * V"_"

   _ENV["bind_parameter"] = V"_" * P"bind" * S"-_" * P"parameter" * V"_"

   _ENV["collation_name"] = V"_" * P"collation" * S"-_" * P"name" * V"_"

   _ENV["commit"] = V"_" * P"commit" * V"_"

   _ENV["create_index"] = V"_" * P"create" * S"-_" * P"index" * V"_"

   _ENV["create_trigger"] = V"_" * P"create" * S"-_" * P"trigger" * V"_"

   _ENV["create_view"] = V"_" * P"create" * S"-_" * P"view" * V"_"

   _ENV["create_virtual_table"] = V"_" * P"create" * S"-_" * P"virtual" *
                                  S"-_" * P"table" * V"_"

   _ENV["delete"] = V"_" * P"delete" * V"_"

   _ENV["detach"] = V"_" * P"detach" * V"_"

   _ENV["drop"] = V"_" * P"drop" * V"_"

   _ENV["filter_clause"] = V"_" * P"filter" * S"-_" * P"clause" * V"_"

   _ENV["insert"] = V"_" * P"insert" * V"_"

   _ENV["over_clause"] = V"_" * P"over" * S"-_" * P"clause" * V"_"

   _ENV["pragma"] = V"_" * P"pragma" * V"_"

   _ENV["raise_function"] = V"_" * P"raise" * S"-_" * P"function" * V"_"

   _ENV["reindex"] = V"_" * P"reindex" * V"_"

   _ENV["release"] = V"_" * P"release" * V"_"

   _ENV["rollback"] = V"_" * P"rollback" * V"_"

   _ENV["savepoint"] = V"_" * P"savepoint" * V"_"

   _ENV["select"] = V"_" * P"select" * V"_"

   _ENV["update"] = V"_" * P"update" * V"_"

   _ENV["vacuum"] = V"_" * P"vacuum" * V"_"

   end

return _sql_fn

